name: Docker build and Bump Version

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  version_bump_docker:
    uses: tucowsinc/wavelo-platforms-automation/.github/workflows/version_docker.yml@1a0118d